---
abstract: 'Módulos para facilitarem a intergração entre a EV e o PayPal.'
author:
  - 'Aware <desenvolvimento@aware.com.br>'
build_requires:
  Data::UUID: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::EstanteSetup: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110440'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Estante-PayPal
recommends:
  Unicode::CheckUTF8: 0
requires:
  Carp: 0
  Config::Any: 0
  JSON::XS: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Traits: 0
  WWW::Mechanize: 0
  perl: 5.014
version: 20110726
